name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore ./API/MsPro.API/MsPro.API.csproj
    - name: Build
      run: dotnet build ./API/MsPro.API/MsPro.API.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./API/API.v1/MedCore_DataAccessTests/MedCore_DataAccessTests.csproj --configuration Release
      
